# Generated by Django 3.0.8 on 2020-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('name', models.CharField(max_length=200, verbose_name='Description')),
                ('last_sale', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Last sale value')),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Market Cap')),
                ('ipo_year', models.IntegerField(verbose_name='IPO Year')),
                ('nasdaq_url', models.URLField()),
            ],
        ),
    ]
