# Generated by Django 3.0.8 on 2020-07-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbol_search', '0002_auto_20200720_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_sale',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Last sale value'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Market Cap'),
        ),
    ]
